services:

  #Api
  promocode-factory-api:                             
    image: 'bimkan/promocode-factory-api:2.0'
    restart: always
    ports:
      - "8091:8080"
    environment:
      - "ConnectionStrings:PromoCodeFactoryDb=Host=promocode-factory-db;Database=promocode_factory_db;Username=postgres;Password=docker"          
    depends_on: 
      - promocode-factory-db
  #Db
  promocode-factory-db:
    image: "postgres:16-alpine"
    container_name: 'promocode-factory-db'
    restart: always 
    ports:
      - "5433:5432"
    environment: 
      - POSTGRES_PASSWORD=docker